version: "3"

networks:
  default:

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "nest_react_todos"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql:rw
    networks:
      - default
  backend:
    build: ./todo-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default
  frontend:
    build: ./todo-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - default

volumes:
  mysql-volume:
